version: 0.2

env:
  variables:
    ECR_REPO: "public.ecr.aws/x8s3d4b4/flask-websocket-app"
    EC2_INSTANCE_ID: "i-0e69f04f648b55bf2"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - yum install -y git

  pre_build:
    commands:
      - echo "Cloning latest code from GitHub..."
      - rm -rf flask-app-test  # Clean previous clone
      - git clone https://github.com/Abhishekpol89/flask-app-test.git flask-app-test
      - cd flask-app-test
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
      - cd ..

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t flask-app-test .
      - docker tag flask-app-test:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $ECR_REPO:latest
      - echo "Deploying using AWS Systems Manager..."
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=$EC2_INSTANCE_ID" \
          --parameters 'commands=[
            "docker pull $ECR_REPO:latest",
            "docker stop flask-websocket-app || true",
            "docker rm flask-websocket-app || true",
            "docker run -d -p 5000:5000 --name flask-websocket-app $ECR_REPO:latest"
          ]' \
          --region us-east-1
