version: 0.2

env:
  variables:
    DOCKERHUB_REPO: "abhishekpol/flask-app-test"  # Replace with your Docker Hub repository name
    DOCKERHUB_USERNAME: "abhishekpol"  # Replace with your Docker Hub username
    DOCKERHUB_PASSWORD: "Abhishek@7868928"  # Replace with your Docker Hub password (or use a Docker Hub token)

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - yum install -y git

  pre_build:
    commands:
      - echo "Cloning latest code from GitHub..."
      - rm -rf flask-app-test  # Clean previous clone
      - git clone https://github.com/Abhishekpol89/flask-app-test.git flask-app-test
      - cd flask-app-test
      - echo "Logging in to Docker Hub..."
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t flask-websocket-app .
      - docker tag flask
